Script started on Fri 20 Nov 2015 07:36:44 AM UTC
bin/rshells_private:~/workspace/cs100/rshell (test) $ ls -a; echo hello&& mkdir DELETE|| echo world; git status
$ ls -a; echo hello&& mkdir DELETE|| echo world; git status
.  ..  .git  DELETE  LICENSE  Makefile	README.md  bin	rhale002  rhale002rubric  src  tests  typescript
hello
mkdir: cannot create directory ‘DELETE’: File exists
world
On branch test
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   src/main.cpp
	modified:   src/rshell.cpp

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bin/
	rhale002
	rhale002rubric
	typescript

no changes added to commit (use "git add" and/or "git commit -a")
$ exit

rhale002@cs_private:~/workspace/cs100/rshell (test) $ exit
exit

Script done on Fri 20 Nov 2015 07:37:13 AM UTC
